name: Deploy to Hetzner

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/pvpankaj/spring-petclinic:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u pvpankaj --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME

      - name: Deploy to Hetzner
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: root
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            cd /opt/apps/petclinic
            docker pull ghcr.io/pvpankaj/spring-petclinic:latest
            docker compose down
            docker compose up -d
            docker image prune -f
